pipeline {
    agent any

    options {
        ansiColor('xterm')
    }

    parameters {
        string(name: 'ENV1', defaultValue: 'dev', description: 'Deployment environment')
    }

    environment {
        VERSION_IMAGE_LABEL = "${MAJOR_MINOR}.${BUILD_NUMBER}-${ENV}"
        REGISTRY_URL="gitea.local.aflorzy.com"
        REGISTRY_CREDENTIALS = credentials('gitea')
        IMAGE_NAME="aflorzy/daytrackr-frontend"
        BRANCH_NAME="${BRANCH_NAME}"
    }

    stages {
        stage ('Checkout SCM') {
            steps {
                git branch: "${BRANCH_NAME}", credentialsId: 'gitea', url: 'git@192.168.1.205:aflorzy/daytrackr-parser.git'
            }
        }
        stage ('Setup') {
            steps {
                sh "docker build -f runner.dockerfile -t runner:latest ."
            }
        }
        stage ('Install Dependencies') {
            environment {
                workspace = pwd()
            }
            steps {
                sh "docker run --rm -v ${workspace}:/workspace runner:latest npm install --configuration=production --prefix /workspace"
            }
        }
        stage ('Run Linting') {
            environment {
                workspace = pwd()
            }
            steps {
                sh "docker run --rm -v ${workspace}:/workspace runner:latest npm run lint:ci --prefix /workspace"
            }
        }
        stage ('Run Tests') {
            environment {
                workspace = pwd()
            }
            steps {
                sh "docker run --rm -v ${workspace}:/workspace runner:latest npm run test:ci --prefix /workspace"
            }
        }
        stage ('Compile') {
            environment {
                workspace = pwd()
            }
            steps {
                sh "docker run --rm -v ${workspace}:/workspace runner:latest npm run build --prefix /workspace"
            }
        }
        stage ('Build Docker Image') {
            steps {
                // Tag with version and with latest
                sh "docker build -t ${REGISTRY_URL}/${IMAGE_NAME}:${VERSION_IMAGE_LABEL} -t ${REGISTRY_URL}/${IMAGE_NAME}:latest ."
            }
        }
        stage ('Push Docker Image to Registry') {
            steps {
                // Log in to the Docker registry
                sh """
                    echo ${REGISTRY_CREDENTIALS_PSW} | docker login ${REGISTRY_URL} -u ${REGISTRY_CREDENTIALS_USR} --password-stdin
                """

                // Push the versioned tag
                sh "docker push ${REGISTRY_URL}/${IMAGE_NAME}:${VERSION_IMAGE_LABEL}"

                // Only push latest if prod env
                if (env.ENV == 'prod') {
                    sh "docker push ${REGISTRY_URL}/${IMAGE_NAME}:latest"
                }
            }
        }
    }
    post {
        always {
            echo 'Log Out of Docker Registry'
            sh "docker logout ${REGISTRY_URL}"
        }
    }
}
