server.port=${SERVER_PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/daytrackr?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:aflorzy}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
logging.file.path=${LOGGING_FILE_PATH:/var/log/tomcat}

entitymanager.packagesToScan=${ENTITYMANAGER_PACKAGESTOSCAN:com.aflorzy.daytrackr.domain}

jwt.secret=${JWT_SECRET:secret}
jwt.expiration=${JWT_EXPIRATION:700000}
