pipeline {
    agent any

    options {
        // This is required if you want to clean before build
        skipDefaultCheckout(true)
        ansiColor('xterm')
    }
    
    parameters {
        choice(name: 'ENV', choices: ['dev', 'prod'], description: 'Select the deployment environment')
        
        string(name: 'MAJOR_MINOR', defaultValue: '1.0', description: 'Major and minor version of build. Patch number set after build.')
    }

    environment {
        VERSION_IMAGE_LABEL = "${MAJOR_MINOR}.${BUILD_NUMBER}-${ENV}"
        REGISTRY_URL="gitea.local.aflorzy.com"
        REGISTRY_CREDENTIALS = credentials('gitea')
        IMAGE_NAME="aflorzy/daytrackr-backend"
        ENV = "${ENV}"
        BRANCH_NAME="${BRANCH_NAME}"
    }
    tools {
        maven "Maven 3.6.3"
        'org.jenkinsci.plugins.docker.commons.tools.DockerTool' 'docker'
    }
    stages {
        stage ('Checkout SCM') {
            steps {
                git branch: "${BRANCH_NAME}", credentialsId: 'gitea', url: 'git@192.168.1.205:aflorzy/daytrackr-backend.git'
            }
        }
        stage ('Build Maven') {
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }
        stage ('Build Docker Image') {
            steps {
                sh "docker build -t ${REGISTRY_URL}/${IMAGE_NAME}:${VERSION_IMAGE_LABEL} -t ${REGISTRY_URL}/${IMAGE_NAME}:latest ."
            }
        }
        stage ('Push Image to Registry') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'gitea', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        // Log in to the Docker registry
                        sh "docker login ${REGISTRY_URL} -u ${DOCKER_USER} -p ${DOCKER_PASS}"

                        def VERSIONED_TAG = "${REGISTRY_URL}/${IMAGE_NAME}:${VERSION_IMAGE_LABEL}"

                        sh "docker push ${VERSIONED_TAG}"

                        // Remove image to save disk space
                        sh "docker image rm -f ${VERSIONED_TAG}"

                        // Conditionally push the latest tag based on the environment
                        if (ENV == 'prod') {
                            def LATEST_TAG = "${REGISTRY_URL}/${IMAGE_NAME}:latest"

                            sh "docker push ${LATEST_TAG}"

                            // Remove image to save disk space
                            sh "docker image rm -f ${LATEST_TAG}"
                        }

                        // Log out from Docker registry
                        sh "docker logout ${REGISTRY_URL}"
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'Log Out of Docker Registry'
            sh "docker logout ${REGISTRY_URL}"
        }
    }
}
